import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { Metadata } from "next";
import { satoshi, zodiak } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${satoshi.variable} ${zodiak.variable} bg-[var(--lgreen3)]`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

// /////
// import "./globals.css"; import Header from "./components/header"; import Footer from "./components/footer"; import { Metadata } from "next"; import { satoshi, zodiak } from "./fonts"; export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app", }; export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) { return ( <html lang="en"> <body className={${satoshi.variable} ${zodiak.variable} bg-[var(--lgreen3)]} > <Header /> <main>{children}</main> <Footer /> </body> </html> ); }
